version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: annasahay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: annasahay
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  app:
    build: .
    container_name: annasahay-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/annasahay?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_volume:
